
const $ = (id) => document.getElementById(id);
async function api(url, options = {}) { const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json" }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Une erreur est survenue."); return data; }
function message(value) { $("message").textContent = value; }
function setBusy(form, busy, label) { const button = form.querySelector("button[type=submit]"); if (!button) return; if (!button.dataset.label) button.dataset.label = button.textContent; button.disabled = busy; button.setAttribute("aria-busy", String(busy)); button.textContent = busy ? label : button.dataset.label; }
async function redirectIfAuthenticated() { const reason = new URLSearchParams(window.location.search).get("reason"); if (reason === "session") message("La session n’a pas été conservée par le navigateur. Vérifiez que vous utilisez la même adresse (localhost ou 127.0.0.1).");
    if (reason === "server") message(new URLSearchParams(window.location.search).get("message") || "Le serveur n’a pas pu vérifier la session."); try { const data = await api("/api/auth/me", { headers: {} }); if (data.user) window.location.replace("/index.html"); } catch (error) { if (reason !== "session") message(error.message); } }
async function login(event) { event.preventDefault(); const form = event.currentTarget; setBusy(form, true, "Connexion..."); message(""); try { const data = await api("/api/auth/login", { method: "POST", body: JSON.stringify({ email: $("email").value.trim(), password: $("password").value }) }); if (!data.user) throw new Error("Connexion impossible."); const session = await api("/api/auth/me", { headers: {} }); if (!session.user) throw new Error("La session n’a pas été créée. Vérifiez l’adresse utilisée dans le navigateur."); window.location.replace("/index.html"); } catch (error) { setBusy(form, false); message(error.message); } }
async function register(event) { event.preventDefault(); const form = event.currentTarget; setBusy(form, true, "Inscription..."); message(""); try { const data = await api("/api/auth/register", { method: "POST", body: JSON.stringify({ name: $("name").value.trim(), email: $("email").value.trim(), password: $("password").value }) }); if (!data.user) throw new Error("Inscription impossible."); window.location.replace("/index.html"); } catch (error) { setBusy(form, false); message(error.message); } }
async function forgot(event) { event.preventDefault(); const form = event.currentTarget; setBusy(form, true, "Envoi..."); message(""); try { const data = await api("/api/auth/forgot", { method: "POST", body: JSON.stringify({ email: $("email").value.trim() }) }); message(data.message); setBusy(form, false); } catch (error) { setBusy(form, false); message(error.message); } }
async function reset(event) { event.preventDefault(); const form = event.currentTarget; setBusy(form, true, "Modification..."); message(""); try { const data = await api("/api/auth/reset", { method: "POST", body: JSON.stringify({ email: $("email").value, token: $("token").value, password: $("password").value }) }); message(data.message); setTimeout(() => window.location.replace("/login.html"), 900); } catch (error) { setBusy(form, false); message(error.message); } }
